---
  - name: Ensure apt-transport-https is installed
    apt: pkg=apt-transport-https state=present

  - name: Add gpg key
    apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch state=present

  - name: Add repository
    apt_repository: repo="deb https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/apt stable main" state=present

  - name: Install package
    apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
    with_items:
      - elasticsearch
      - kibana

  - name: Configurate elasticsearch.yml
    template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=elasticsearch
    notify:
      - restart elasticsearch

  - name: Configurate kibana.yml
    template: src=kibana.yml.j2 dest=/etc/kibana/kibana.yml owner=root group=root
    notify:
      - restart kibana

  - import_tasks: xpack.yml

  - name: Ensure running
    service: name=elasticsearch state=started

  - name: Wait for node to be ready
    wait_for: host=localhost port=9200
