---
  - name: Adding PHP-{{ php_version }} repository
    apt_repository: repo=ppa:ondrej/php

  - name: Installing packages
    apt: pkg=php{{ php_version }}-{{ item }} update_cache=true
    with_items:
      - dev
      - cli
      - fpm
      - gd
      - json
      - curl
      - mysql
      - sqlite3
      - intl
      - mcrypt
      - mbstring
      - zip
      - xml
      - common
      - opcache
      - xdebug
      - apcu
    notify:
      - restart php-fpm

  - name: Create custom configuration
    template: src=custom.ini.j2 dest=/etc/php/{{ php_version }}/mods-available/custom.ini owner=root group=root
    notify:
      - restart php-fpm

  - name: Create configuration links
    file: src=/etc/php/{{ php_version }}/mods-available/custom.ini dest=/etc/php/{{ php_version }}/{{ item }}/conf.d/20-custom.ini state=link
    with_items: [fpm, cli]
    notify:
      - restart php-fpm

  - import_tasks: pools.yml

  - import_tasks: composer.yml

  - name: Create debug file
    copy: src=files/debug dest=/usr/local/bin/debug mode=755