- name: PHP 7.1 repository
  apt_repository: repo=ppa:ondrej/php
- name: Installing packages
  apt: pkg={{ item }} update_cache=true
  with_items:
    - php7.1-dev
    - php7.1-cli
    - php7.1-fpm
    - php7.1-gd
    - php7.1-json
    - php7.1-curl
    - php7.1-mysql
    - php7.1-intl
    - php7.1-mcrypt
    - php7.1-common
    - php7.1-xdebug
- name: Create custom configuration
  template: src=custom.ini.j2 dest=/etc/php/7.1/mods-available/custom.ini owner=root group=root
- name: Create configuration links
  file: src=/etc/php/7.1/mods-available/custom.ini dest=/etc/php/7.1/{{ item }}/conf.d/20-custom.ini state=link
  with_items: [fpm, cli]
  notify:
    - restart php7.1-fpm
