---
  - name: Adding PHP-{{ php_version }} repository
    apt_repository: repo=ppa:ondrej/php

  - name: Installing packages
    apt: pkg=php{{ php_version }}-{{ item }} update_cache=true
    with_items:
      - dev
      - cli
      - fpm
      - gd
      - json
      - curl
      - mysql
      - sqlite3
      - intl
      - mcrypt
      - mbstring
      - zip
      - xml
      - common
      - opcache
      - xdebug

  - name: Create custom configuration
    template: src=custom.ini.j2 dest=/etc/php/{{ php_version }}/mods-available/custom.ini owner=root group=root

  - name: Create configuration links
    file: src=/etc/php/{{ php_version }}/mods-available/custom.ini dest=/etc/php/{{ php_version }}/{{ item }}/conf.d/20-custom.ini state=link
    with_items: [fpm, cli]
    notify:
      - restart php-fpm

  - name: Remove default pool
    file: path=/etc/php/{{ php_version }}/fpm/pool.d/www.conf state=absent

  - name: Create pools
    template: src=pool.conf.j2 dest=/etc/php/{{ php_version }}/fpm/pool.d/{{ item.name }}.conf owner=root group=root
    with_items: "{{ php_pools }}"
    notify:
      - restart php-fpm