---
  - name: Setup
    hosts: all
    become: True
    vars:
        box_address: "{{ hostvars[inventory_hostname].ansible_all_ipv4_addresses[1] }}"
        box_address_parts: "{{ box_address.split('.') }}"
        box_gateway: "{{ box_address_parts[0] + '.' + box_address_parts[1] + '.' + box_address_parts[2] + '.1' }}"
    roles:
      - role: php
        php_xdebug_remote_host: "{{ box_gateway }}"
        php_pools:
          - { name: vm.dev, user: vagrant, group: vagrant }

      - role: nginx
        nginx_vhosts:
          symfony:
            - { name: vm.local, document_root: /home/vagrant/public_html/web, document_index: app_dev }

      - role: mysql
        mysql_bind_address: 0.0.0.0
        mysql_users:
          - { name: root, host: "{{ box_gateway }}", password: 'root', privileges: '*.*:ALL,GRANT' }

      # - role: nodejs
      #   npm_global_packages: [bower, gulp]

      - role: zsh
        ZSH_EXTRA: >
          alias dev='php bin/console --env=dev'
          alias prod='php bin/console --env=prod'

    pre_tasks:
      - name: Install packages
        apt: pkg={{ item }} update_cache=true cache_valid_time=3600
        with_items:
          - build-essential
          - htop
          - curl
          - unzip
          - make
          - python-software-properties
          - openjdk-7-jre
          - python3-pip

      - name: Install common pip packages
        pip: name={{ item }} executable=/usr/bin/pip3 state=present
        with_items:
          - httpie

      - name: Generate en_US.UTF-8 Locale
        locale_gen: name=en_US.UTF-8 state=present
