---
  - name: Setup
    hosts: all
    become: True
    vars_files:
      - vars/main.yml
    roles:
      - role: php
      - role: nginx
      - role: mysql
      - role: zsh

      - role: java
      - role: elasticsearch

    pre_tasks:
      - name: Install packages
        apt: pkg={{ item }} update_cache=true cache_valid_time=3600
        with_items:
          - build-essential
          - htop
          - curl
          - unzip
          - make
          - python-software-properties
          - openjdk-7-jre
          - python3-pip

      - name: Install common pip packages
        pip: name={{ item }} executable=/usr/bin/pip3 state=present
        with_items:
          - httpie

      - name: Generate en_US.UTF-8 Locale
        locale_gen: name=en_US.UTF-8 state=present
