---
- name: Setup web server
  hosts: dev-vm
  sudo: True
  roles:
    - role: php
    - role: nginx
      nginx_document_root: /var/www/public_html/web
    - role: mysql
      mysql_bind_address: 0.0.0.0
    - role: nodejs
      npm_global_packages: [bower, gulp]
    - role: zsh
      ZSH_EXTRA: >
        alias dev='php app/console --env=dev'
        alias prod='php app/console --env=prod'
  vars:
    symfony_version: latest
  pre_tasks:
    - name: Install packages
      apt: pkg={{ item }} update_cache=true cache_valid_time=3600
      with_items:
        - build-essential
        - htop
        - curl
  tasks:
    - name: Install Composer - Dependency Manager for PHP
      shell: curl -sS https://getcomposer.org/installer | php -- --filename=composer
      args:
        chdir: /usr/local/bin
        creates: /usr/local/bin/composer
    - name: Install Symfony Installer
      shell: sudo curl -LsS http://symfony.com/installer -o /usr/local/bin/symfony
      args:
        creates: /usr/local/bin/symfony
    - name: Provide permissions for Symfony Installer
      file: path=/usr/local/bin/symfony mode="a+x"
    - name: Create debug env file
      copy: src=files/debug dest=/usr/local/bin/debug mode=755
