---
- name: Setup new symfony project
  hosts: dev-vm
  vars:
    symfony_version: latest
    symfony_directory: /var/www/public_html
  tasks:
    - name: Collecting public_html files
      shell: ls -la {{ symfony_directory }} | awk '{ print $9 }' | tail -n +4
      register: phtml
    - name: Cleaning up public_html directory
      file: path={{ symfony_directory }}/{{ item }} state=absent
      when: phtml.stdout_lines|length > 0
      with_items: phtml.stdout_lines
    - name: Creating new symfony project
      shell: symfony new {{ symfony_directory }} {{ symfony_version }}
      args:
        creates: /var/www/public_html/web
