- name: Adding repository
  shell: curl -sL https://deb.nodesource.com/setup | sudo bash -
  args:
    creates: /etc/apt/sources.list.d/nodesource.list
- name: Install package
  apt: pkg=nodejs update_cache=true cache_valid_time=3600
- name: Install npm global packages
  npm: name={{ item }} global=true state=present
  with_items: npm_global_packages
