---
  - name: Install package
    apt: pkg=nginx update_cache=true cache_valid_time=3600

  - name: Copy nginx configuration file
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify:
      - restart nginx

  - import_tasks: symfony.yml

  - import_tasks: kibana.yml