---
  - name: Install prerequsites
    apt: pkg={{ item }}
    with_items:
      - ssh
      - rsync
  - name: Create group
    group: name=hadoop state=present
  - name: Create user
    user: >
      name=hduser
      password={{ hadoop_user_pass }}
      group=hadoop
      generate_ssh_key=yes
  - name: Lookup saved ssh hostkey for this host
    shell: cat /home/hduser/.ssh/id_rsa.pub
    sudo: true
    ignore_errors: True
    register: pub
  - name: Authorize hadoop user key
    authorized_key: >
      user=hduser
      key="{{ pub.stdout }}"
      path="/home/hduser/.ssh/authorized_keys"
      state=present
  - name: Download Hadoop
    get_url: >
      url={{ hadoop_download_url }}
      dest=/tmp/hadoop.tar.gz
  - name: Extract Hadoop
    unarchive: src=/tmp/hadoop.tar.gz dest=/usr/local copy=no
    args:
      creates: '/usr/local/hadoop'
  - name: Rename hadoop folder
    command: "mv /usr/local/{{ hadoop_name }} /usr/local/hadoop"
    args:
      creates: /usr/local/hadoop
  - name: Fix ownership
    file: >
      state=directory
      path=/usr/local/hadoop
      owner=hduser
      group=hadoop
      recurse=yes
  - name: Export env variables
    lineinfile: >
      dest=/home/hduser/.profile
      line="{{ item }}"
    with_items:
      - "export HADOOP_PREFIX=/usr/local/hadoop"
      - "export JAVA_HOME=/usr/local/java"
      - "PATH=$PATH:$JAVA_HOME\bin:$HADOOP_PREFIX/sbin:$HADOOP_PREFIX/bin"
    sudo: true
  - name: Disable IPV6
    lineinfile: >
      dest=/etc/sysctl.conf
      line="{{ item }}"
    with_items:
      - "net.ipv6.conf.all.disable_ipv6 = 1"
      - "net.ipv6.conf.default.disable_ipv6 = 1"
      - "net.ipv6.conf.lo.disable_ipv6 = 1"
    notify:
      - Restart system config
  - name: Setup hadoop-env.sh
    template: src=hadoop-env.sh.j2 dest=/usr/local/hadoop/etc/hadoop/hadoop-env.sh
  - name: Create tmp directory for hadoop
    file: >
      dest={{ hadoop_tmp_dir }}
      state=directory
      owner=hduser
      group=hadoop
  - name: Setup core-site.xml
    template: src=core-site.xml.j2 dest=/usr/local/hadoop/etc/hadoop/core-site.xml
  - name: Setup mapred-site.xml
    template: src=mapred-site.xml.j2 dest=/usr/local/hadoop/etc/hadoop/mapred-site.xml
  - name: Create namenode directory
    file: >
      dest=/usr/local/hadoop_store/hdfs/namenode
      state=directory
      owner=hduser
      group=hadoop
  - name: Create datanode directory
    file: >
      dest=/usr/local/hadoop_store/hdfs/datanode
      state=directory
      owner=hduser
      group=hadoop
  - name: Setup hdfs-site.xml
    template: src=hdfs-site.xml dest=/usr/local/hadoop/etc/hadoop/hdfs-site.xml
  - name: Format hadoop
    become_user: hduser
    shell: hadoop namenode -format
