---
  - name: Create empty databases
    mysql_db: >
      login_user=root
      login_password={{ mysql_root_pass }}
      name={{ item }}
      state=present
    with_items: "{{ mysql_databases }}"
