---
  - name: Installing packages
    apt: name={{ item }} state=installed update_cache=yes cache_valid_time=3600
    with_items:
      - mysql-common-5.6
      - mysql-server-5.6
      - mysql-client-5.6
      - python-mysqldb

  - name: Copy the configuration file (my.cnf)
    template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
    notify:
      - restart mysql

  - import_tasks: users.yml

  - import_tasks: databases.yml