---
  - name: Update MySQL root password for all root accounts
    mysql_user: >
      name=root
      host={{ item }}
      password={{ mysql_root_pass }}
      priv=*.*:ALL,GRANT
      state=present
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost

  - name: Copy the root credentials as .my.cnf file
    template: >
      src=user.cnf.j2
      dest=/root/.my.cnf
      mode=0644
      owner=root
      group=root

  - name: Ensure Anonymous user(s) are not in the database
    mysql_user: name='' host={{ item }} state=absent
    with_items:
      - localhost
      - "{{ ansible_hostname }}"

  - name: Create additional mysql user(s)
    mysql_user: >
      name={{ item.name }}
      host={{ item.host }}
      password={{ item.password }}
      login_user=root
      login_password={{ mysql_root_pass }}
      priv={{ item.priv }}
      state=present
    with_items: "{{ mysql_users }}"

