---
  - name: Installation
    apt: >
      pkg='rabbitmq-server'
      state=present
      install_recommends=no

  - name: Enable rabbitmq_management plugin
    rabbitmq_plugin: >
      name='rabbitmq_management'
      state=enabled

  - name: Add users
    rabbitmq_user: >
      user={{ item.name }}
      password={{ item.pass }}
      vhost={{ item.vhost }}
      configure_priv={{ item.configure_priv }}
      read_priv={{ item.read_priv }}
      write_priv={{ item.write_priv }}
      tags={{ item.tags }}
      state=present
    with_items: rabbitmq_users
