---
  - name: Ensure wget exists
    apt: pkg=wget state=present

  - name: Download oracle jdk
    get_url: dest=/tmp/java.tar.gz headers="Cookie:oraclelicense=accept-securebackup-cookie" url={{ java_download_url }}

  - name: Extract Java archive
    command: 'tar -xzf /tmp/java.tar.gz -C /tmp'
    args:
      creates: '/tmp/{{ java_name }}'

  - name: Create final Java folder
    file: >
      path={{ java_home }}
      state=directory

  - name: Fix ownership
    file: >
      state=directory
      path=/tmp/{{ java_name }}
      owner=root
      group=root
      recurse=yes

  - name: Move Java to final folder
    shell: "mv /tmp/{{ java_name }}/* {{ java_home }}"
    args:
      creates: '{{ java_home }}/bin'

  - name: Cleanup tmp
    file: >
      path=/tmp/{{ java_name }}
      state=absent

  - name: Install Java for system
    command: 'update-alternatives --install "/usr/bin/{{ item }}" "{{ item }}" "/usr/local/java/bin/{{ item }}" 1'
    with_items:
      - java
      - javac
      - javaws

  - name: Make Java available for system
    command: 'update-alternatives --set {{ item }} /usr/local/java/bin/{{ item }}'
    with_items:
      - java
      - javac
      - javaws
